---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  git-legal:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "Gemfile*"
  - "*.gemspec"
  - "**.rb"
exclude_paths:
- "spec/**/*"
