---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  git-legal:
    enabled: true
    config:
      # For the resume gem itself
      allow_unknown_libraries: true
      license_whitelist: ["GNU General Public License 3.0"]
  rubocop:
    enabled: true
ratings:
  paths:
  - "Gemfile.lock"
  - "*.gemspec"
  - "**.rb"
exclude_paths:
- "spec/**/*"
