# Contains personal customisations of Rubocop default rules
require: rubocop-rspec

AllCops:
  Exclude:
    - "resume.rb"
    - "strings_en.rb"
    - "strings_it.rb"
    - "strings_ja.rb"
    # FIXME: Disabled for now...
    # - "spec/**/*"
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleExpectations:
  Max: 5

# NOTE: This deep nesting mostly due to the wide range of paths that gem
# installation and file fetching can take, and the different errors that
# can occur.
RSpec/NestedGroups:
  MaxNesting: 8

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

# FIXME: Disabled for now...
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
