# Contains personal customisations of Rubocop default rules
# require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "resume.rb"
    - "strings_en.rb"
    - "strings_it.rb"
    - "strings_ja.rb"
    # FIXME: Disabled for now...
    - "spec/**/*"

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

# FIXME: Disabled for now...
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
