# Contains personal customisations of Rubocop default rules
require: rubocop-rspec

AllCops:
  Exclude:
    - "resume.rb"
    - "strings_en.rb"
    - "strings_it.rb"
    - "strings_ja.rb"
    # NOTE: Although this exclusion is in the default Rubocop config, it seems
    # that CI still goes looking in the vendor directory and attempts to
    # scan all files in all gems, so make the exclusion explicit here.
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleExpectations:
  Max: 5

# NOTE: This deep nesting mostly due to the wide range of paths that gem
# installation and file fetching can take, and the different errors that
# can occur.
RSpec/NestedGroups:
  MaxNesting: 8

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

# NOTE: PDF generation requires string mutation, so this can't be used for now.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
