checks:
  ruby:
    code_rating: true
    duplicate_code: true
tools:
  rubocop:
    use_native_config: true
filter:
  excluded_paths:
    - spec/*
    - vendor/*
build:
  environment:
    ruby: 2.4.1
  project_setup:
    before:
      - cd /home/runner/.rbenv/plugins/ruby-build && git pull && cd -
      - rbenv install -l
      - rbenv install 2.4.1
      - rbenv global 2.4.1
      - ruby -v
      - gem update --system
      - gem install bundler i18n rspec
  tests:
    before:
      - bin/bundle-audit check --update
      - bin/rubocop --display-cop-names
      - printf "yes\nno\n" | bin/resume
      - bin/resume -l it <<< "no\n"
      - printf "yes\nno\n" | bin/resume -l ja
      - bin/rake resume
      - ruby resume.rb <<< "no\n"
      - ruby resume.rb -l it <<< "no\n"
      - ruby resume.rb -l ja <<< "no\n"
    override:
      -
        command: bin/rspec spec/ --no-drb --format progress
        environment:
          'SCRUTINIZER_CC_FILE': 'my-coverage'
        coverage:
          file: 'my-coverage'
          format: 'rb-cc'
checks:
  ruby:
    code_rating: true
    duplicate_code: true
