# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
language: ruby
cache: bundler
rvm:
  - 2.4.0
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  # Prevent issues like the following happening:
  # https://github.com/sickill/rainbow/issues/44
  - gem update --system
  - gem install i18n rspec
  # - bundle install
script:
  - bin/bundle-audit check --update
  - bin/rspec spec/ --no-drb --format progress
  - bin/rubocop --display-cop-names
  # NOTE: The 'no's below indicate not wanting to get CI to attempt to open
  # the generated PDF
  # Agree to installing prawn and prawn-table gems
  - bin/resume <<< "yes\nno\n"
  - bin/resume -l it <<< "no\n"
  # Agree to installing rubyzip and downloading custom font
  - bin/resume -l ja <<< "yes\nno\n"
  - bin/rake resume
  - ruby resume.rb <<< "no\n"
  - ruby resume.rb -l it <<< "no\n"
  - ruby resume.rb -l ja <<< "no\n"
after_success:
  - bin/codeclimate-test-reporter
