# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
language: ruby
cache: bundler
rvm:
  - 2.4.0
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  # Prevent issues like the following happening:
  # https://github.com/sickill/rainbow/issues/44
  - gem update --system
  - gem install i18n rspec
  - bundle install
script:
  - bin/bundle-audit check --update
  - bin/rspec spec/ --no-drb --format progress
  - bin/rubocop --display-cop-names
  - printf 'no\n' | bin/resume
  - printf 'no\n' | bin/resume -l it
  - printf 'yes\nno\n' | bin/resume -l ja
  - bin/rake resume
  - printf 'no\n' | ruby resume.rb
  - printf 'no\n' | ruby resume.rb -l it
  - printf 'no\n' | ruby resume.rb -l ja
after_success:
  - bin/codeclimate-test-reporter
