# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
language: ruby
cache: bundler
rvm:
- 2.3.2
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
script:
- bin/rspec spec/ --no-drb --format progress
- bin/rake resume
