version: 1.0.{build}-{branch}
skip_tags: true
build: off
environment:
  matrix:
    - ruby_version: 23
install:
  # AppVeyor currently only supports up to Ruby 2.3.3
  - SET CUSTOM_RUBY_VERSION=2.3.3
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  # Attempt to get around the error
  # OpenSSL::SSL::SSLError:
  #   SSL_connect returned=1 errno=0 state=error: certificate verify failed
  # that occurs when trying to go and fetch a file remotely
  - choco install wget
  - wget https://curl.haxx.se/ca/cacert.pem -O C:\cacert.pem && setx /M SSL_CERT_FILE "C:\cacert.pem"
  - gem update --system
  - update_rubygems
  - gem uninstall bundler -a -x
  - gem install bundler i18n rspec
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
test_script:
  - bundle exec bundle-audit check --update
  - bundle exec rspec spec/ --no-drb --format progress
  - bundle exec rubocop --display-cop-names
  - bundle exec resume <<< "no\n"
  - bundle exec resume -l it <<< "no\n"
  - printf "yes\nno\n" | bundle exec resume -l ja
  - bundle exec rake resume
  - ruby resume.rb <<< "no\n"
  - ruby resume.rb -l it <<< "no\n"
  - ruby resume.rb -l ja <<< "no\n"
