version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          working_directory: ~/paulfioravanti/resume
          command: rm -f paulfioravanti/resume/.rvmrc; echo 2.5.0 > paulfioravanti/resume/.ruby-version; rvm use 2.5.0 --default
      - run: gem install bundler i18n rspec
      - run: gem update --system
      - run: rvm use 2.5.0
      - run:
          command: bundle install
          no_output_timeout: 180s
      - run: bin/bundle-audit check --update
      - run: bin/license_finder
      - run: bin/rspec spec/ --no-drb --format progress
      - run: bin/rubocop --display-cop-names
      - run: bin/resume <<< "no\n"
      - run: bin/resume -l it <<< "no\n"
      - run: printf "yes\nno\n" | bin/resume -l ja
      - run: bin/rake resume
      - run: ruby resume.rb <<< "no\n"
      - run: ruby resume.rb -l it <<< "no\n"
      - run: ruby resume.rb -l ja <<< "no\n"
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
